baseURL: 'http://www.adrianmoreno.info/'
languageCode: en-us
title: 'Adrián Moreno Peña · Web & Mobile Developer, all-around coder'
DefaultContentLanguage: en
theme: miniport

Languages:
  en:
    weight: 1
  es:
    weight: 2
